web:
    image: hitalos/laravel:latest
    ports:
        - 8080:80
        - 443:443
    volumes:
        - ./:/var/www
    links:
        - db
db:
    image: mysql:5.7
    volumes:
        - /var/lib/mysql
    environment:
        # with mysql
        MYSQL_DATABASE: fescc796_sge
        MYSQL_USER: fescc796_laravel
        MYSQL_PASSWORD: cnX,kรง32